# configs/models/unet_legacy.yaml

# Defines the architecture for the legacy HopperNetLite model.

name: ModularHopperNet
record_id: HopperNetLite
params:
  # General model parameters
  num_groups: 8
  in_channels: 3
  upsample_mode: 'bilinear'
  out_channels:
    wing: 1
    spots: 1
    veins: 1
    domains: 3 # 2 + background

  # --- Architecture Definition ---

  encoder_configs:
    stem:
      out_channels: 8
      stride: 1
      concat: true
    encoder0_ds:
      out_channels: 8
      stride: 2
      concat: false
    encoder1_mix:
      out_channels: 16
      stride: 1
      concat: true
    encoder1_ds:
      out_channels: 32
      stride: 2
      concat: false

  bottleneck_configs:
    b_neck1:
      out_channels: 64
    b_neck2:
      out_channels: 64

  decoder_configs:
    decoder1:
      # Upsample(64) -> Reduce(64->32) -> Concat(32 + skip(16)) -> Mixer
      reduce_channels: 32
      mixer_out_channels: [32, 16]
    decoder0:
      # Upsample(16) -> Concat(16 + skip(8)) -> Mixer (no reduction)
      reduce_channels: null
      mixer_out_channels: [16, 16]