experiment_id: temp_demo #hopperscapes_demo
savedir: ./outputs/demo/models

# Dataset configurations
image_file_exts:
- .png
- .jpg
image_transforms:
  ResizeToLongestSide:
    image_side_length: 512
  PrepareImageTensor: {}
mask_transforms:
  ResizeToLongestSide:
    image_side_length: 512

# Model configurations
in_channels: 3
out_channels:
  wing: 1
  veins: 1
  spots: 1
  domains: 3
num_groups: 8
upsample_mode: bilinear
encoder_configs:
    stem:
      out_channels: 8
      stride: 1
      concat: true
    encoder0_ds:
      out_channels: 8
      stride: 2
      concat: false
    encoder1_mix:
      out_channels: 16
      stride: 1
      concat: true
    encoder1_ds:
      out_channels: 32
      stride: 2
      concat: false

bottleneck_configs:
  b_neck1:
    out_channels: 64
  b_neck2:
    out_channels: 64

decoder_configs:
  decoder1:
    # Upsample(64) -> Reduce(64->32) -> Concat(32 + skip(16)) -> Mixer
    reduce_channels: 32
    mixer_out_channels: [32, 16]
  decoder0:
    # Upsample(16) -> Concat(16 + skip(8)) -> Mixer
    reduce_channels: null # no reduction
    mixer_out_channels: [16, 16]

# Training configurations
device: cpu # cpu, cuda, mps
batch_size: 4
valid_split: 0.1
random_seed: 43
num_workers: 4
epochs: 300
learning_rate: 6.0e-05
weight_decay: 0.0
lr_scheduler: null # cosine
lr_scheduler_params:
  T_max: 300
  eta_min: 1e-6
warmup_epochs: 20
warmup_lr: 1.0e-06
enable_dynamic_freeze: false
freeze_patience: 15 # epochs
checkpoint_every: 10
log_every: 1
save_best: true
clip_gradients: true
max_grad_norm: 1.0

# Loss configurations
total_loss_weights:
  wing: 1.0
  veins: 1.0
  spots: 1.0
  domains: 1.0
dice_thresholds_to_freeze_heads:
  wing: 0.75
  veins: 0.9
  spots: 0.95
  domains: 1.
loss_function_configs:
  wing:
    bce:
      weight: 1.0
      params:
        pos_weight: 5.0
    soft_dice:
      weight: 1.0
      params: {}
  veins:
    bce:
      weight: 0.5
      params:
        pos_weight: 100.0
    soft_dice:
      weight: 2.0
      params: {}
    cldice:
      weight: 2.0
      params: {}
  spots:
    focal:
      weight: 1.0
      params:
        alpha: 0.85
        gamma: 2.0
    soft_dice:
      weight: 1.0
      params: {}
  domains:
    ce:
      weight: 0.5
      params: {}
    soft_dice:
      weight: 0.5
      params:
        num_classes: 3
freeze_heads:
  wing: false
  veins: true
  spots: false
  domains: false
dice_scores_to_track:
  wing: soft_dice
  veins: cldice
  spots: soft_dice
  domains: soft_dice
