name: tests

on: [push, pull_request]          # run for every push and PR

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4        # pulls your code
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"          # match your README badge
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .
          
      - name: Run tests
        run: python -m pytest -q tests
